---


- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nmap
    - vim
    - lynx
    - sysstat
    - thunderbird
    - vagrant
    - chromium-browser
    - boinc-manager
    - docker.io
    - docker-compose
    - steam

- name: clone pyenv
  git:
    clone: yes
    depth: 1
    dest: "{{ home_path }}/.pyenv"
    repo: https://github.com/pyenv/pyenv.git
    update: yes

- name: update permissions on .pyen
  file:
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: 0700
    path: "{{ home_path }}/.pyenv"    

- name: add to bashrc
  lineinfile:
    backup: yes
    create: yes
    path: "{{ home_path }}/.bashrc"
    line: "{{ item }}"
    mode: 0700
    state: present
  with_items:
    - export PYENV_ROOT="$HOME/.pyenv"
    - export PATH="$PYENV_ROOT/bin:$PATH"
    - eval "$(pyenv init -)"
