---



- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nmap
    - chef
    - lynx
    - thunderbird
    - duplicity
    - vagrant
    - packer
    - virtualbox
    - virtualbox-guest-additions-iso
