# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b12170100bacb26273f7ad10441aa467c63bafd932f5316475d9eaeb0edf12f17b4aaa0f389637ae7f709b2367201924ace592f6c9114d03347eaba245b3e68e

test:
  secret_key_base: 2554d64ce3f1d44010da5246213bc8f434c64278c57d134157ba16917a12e18b3d5b5cd3ad029d7810abc39fb8059e26accda6eb28e07be5da8fbd89d545fcee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
